// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgBUi4-H4oQMQXLc2P8vPkmv4_Pgc51io',
    appId: '1:393811126736:web:7f0e312a5874b9e3aab1d5',
    messagingSenderId: '393811126736',
    projectId: 'my-ioc-app-demo',
    authDomain: 'my-ioc-app-demo.firebaseapp.com',
    storageBucket: 'my-ioc-app-demo.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXPTISSPGNP1EYX9VvkrhtKbqczdwK66A',
    appId: '1:393811126736:android:210f4e7733708588aab1d5',
    messagingSenderId: '393811126736',
    projectId: 'my-ioc-app-demo',
    storageBucket: 'my-ioc-app-demo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCz3Ct2e-hjdYSoAKZeavEe2qaZnvD5Zas',
    appId: '1:393811126736:ios:19243f8c524bb0faaab1d5',
    messagingSenderId: '393811126736',
    projectId: 'my-ioc-app-demo',
    storageBucket: 'my-ioc-app-demo.appspot.com',
    iosBundleId: 'com.example.iocAppDemo1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCz3Ct2e-hjdYSoAKZeavEe2qaZnvD5Zas',
    appId: '1:393811126736:ios:3569789d26120ecfaab1d5',
    messagingSenderId: '393811126736',
    projectId: 'my-ioc-app-demo',
    storageBucket: 'my-ioc-app-demo.appspot.com',
    iosBundleId: 'com.example.iocAppDemo1.RunnerTests',
  );
}
